### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by whiskeysierra** [whiskeysierra/compass#14]
- Authentication and authorization
- optional, can be disabled
- pluggable security
- oauth2 module (based on Zalando IAM)
- user management
- permissions

**Comment by lukasniemeier-zalando** [comment]
1. Is authorization needed at all? Any reason to not always allow read and write?
2. Can we keep it simple by always allowing global access (all keys/values)?

**Comment by whiskeysierra** [comment]
Not sure if it's actually needed. As long as it's running in a secure environment (AWS account, no public IP/ELB) it should be fine. Any frontend on top that is accessible from the outside probably needs something, but that could be done in the UI then. The only part where I think it could be useful is the history, i.e. keeping track of changes including the user who did it.

**Comment by whiskeysierra** [comment]
I'm closing it for now.
