### ISSUE TITLE
Concepts

### ISSUE THREAD

**Issue by whiskeysierra** [whiskeysierra/compass#6]
e.g. using https://en.wikipedia.org/wiki/Hypercube

**Comment by AlexanderYastrebov** [comment]
Yeah, what a hell are you working on? :)

**Comment by whiskeysierra** [comment]
https://docs.google.com/presentation/d/1ynXsGKggbQqOVOMmxTGGrlcCQfQSNYI7eAZGcZNKRxc/edit?usp=sharing
